### ISSUE TITLE
Add docs how to add plugin to Stylelint config

### ISSUE THREAD

**Issue by ai** [mrhenry/stylelint-mrhenry#14]
Now it is hard to understand how to add it.

Also, it is strange that rule name is `plugin/stylelint-mrhenry-nesting`, and not `@mrhenry/stylelint-mrhenry-nesting` or something with correct prefix.

**Comment by romainmenke** [comment]
Thank you for the feedback @ai!

I've made some changes : https://github.com/mrhenry/stylelint-mrhenry/pull/15

- The package and rule names now have the same prefix : `@mrhenry/stylelint-mrhenry-*`
- I've added install docs to each readme : https://github.com/mrhenry/stylelint-mrhenry/blob/31d844935b1659a0e72601e6dbe63b8ca0ec38d7/packages/nesting/README.md

Is there something that I have overlooked that would help users?

**Comment by ai** [comment]
Great! Exactly what will help users!

**Comment by romainmenke** [comment]
This has been released, thank you again
