### ISSUE TITLE
Add custom at-rules support to nesting plugin

### ISSUE THREAD

**Issue by ai** [mrhenry/stylelint-mrhenry#16]
I sometimes use `@mixin` from `postcss-mixins` to reduce code duplication, but `nesting` rules doesn’t allow it.

If we want to fix it, I see 2 options:

1. Allow to specify unknown at-rules. Good idea for the future, if we don't want to change rule on any new at-rule in CSS spec.
2. Add options with allow-list of at-rules.

**Comment by romainmenke** [comment]
I always forget about `@mixin` :)

A plugin option with an allow list makes sense.
This is also good escape hatch if a new conditional rule is added to the CSS specification.

**Comment by romainmenke** [comment]
@ai `ignoreAtRules` has been added : https://github.com/mrhenry/stylelint-mrhenry/tree/main/packages/nesting#optional-secondary-options

Does this solve the issue fully?

**Comment by ai** [comment]
Yes, it should
